version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "9000:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/fullchain1.pem:/etc/ssl/certs/fullchain1.pem
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/privkey1.pem:/etc/ssl/private/privkey1.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  net:
  webnet:
