version: '3.8'

services:
  nginx:
    container_name: seolo-nginx
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/fullchain1.pem:/etc/ssl/certs/fullchain1.pem
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/privkey1.pem:/etc/ssl/private/privkey1.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - front-web-dist:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - back
      - front-web
    networks:
      - jenkins-network

  back:
    container_name: seolo-back
    build:
      context: ../backend/seolo
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network

  front-web:
    container_name: seolo-front-web
    build:
      context: ../frontend/web
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - jenkins-network
    depends_on:
      - back

networks:
  jenkins-network:
    external: true
