version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/fullchain1.pem:/etc/ssl/certs/fullchain1.pem
      - /home/ubuntu/certificates/k10c104.p.ssafy.io/privkey1.pem:/etc/ssl/private/privkey1.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/web/dist:/usr/share/nginx/html  # Nginx가 직접 정적 파일을 서빙
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true