version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped