version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/k10c104.p.ssafy.io/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/k10c104.p.ssafy.io/privkey.pem:/etc/ssl/private/privkey.pem
    restart: unless-stopped